name: Docker Image CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag face-recognition:latest
    - name: Tag Docker Image
      run: docker image tag face-recognition:latest kz16/face-recognition:latest
    - name: Push the Docker image
      run: docker image push kz16/face-recognition:latest
